### ISSUE TITLE
Error compiling on GCC 10.2.0

### ISSUE THREAD

**Issue by Wunkolo** [MerryMage/dynarmic#553]
Recently pulled at https://github.com/MerryMage/dynarmic/commit/0e1112b7df77ae55a62a51622940d5c8f9e8c84c and I'm experiencing errors when trying to compile on the `ASSERT` here, where `N` is `0`:

https://github.com/MerryMage/dynarmic/blob/34f4d9945431ee82d4d603aa1e7b89b35594d2cf/src/frontend/decoder/decoder_detail.h#L88-L90

I'm currently trying to build the project on its own and not as a master-project(so `DYNARMIC_WARNINGS_AS_ERRORS` is true). It seems to build fine on clang 10.0.1.

```
/dynarmic/src/./frontend/decoder/decoder_detail.h:88:34: error: comparison of unsigned expression in ‘< 0’ is always false [-Werror=type-limits]
   88 |                 ASSERT(arg_index < N);
/dynarmic/src/./common/unlikely.h:9:45: note: in definition of macro ‘UNLIKELY’
    9 |     #define UNLIKELY(x) __builtin_expect(!!(x), 0)
      |                                             ^
/dynarmic/src/./frontend/decoder/decoder_detail.h:88:17: note: in expansion of macro ‘ASSERT’
   88 |                 ASSERT(arg_index < N);
      |
```

First time going through the code base so I'm not sure what the obvious fix would be but it looks like there can probably be a specialized case for `N = 0` as the general case template here it will cause zero-sized `std::array`s to be created and indexed into which is [undefined behavior](https://en.cppreference.com/w/cpp/container/array/operator_at):

```cpp
// GetArgInfo<0>
std::array<opcode_type, 0> masks = {};
std::array<size_t, 0> shifts = {};
size_t arg_index = 0;
...
masks[0] = ...
```

**Comment by Wunkolo** [comment]
Turns out clang _does_ get the error and I was using stale build files

I'm able to compile fine on gcc and clang with this modification:
```diff
- ASSERT(arg_index < N);
+ if constexpr(N) ASSERT(arg_index < N);
```
though still, very undefined behavior.

**Comment by MerryMage** [comment]
Should be closed by 46f96904d.
