### ISSUE TITLE
-Werror build fails for Clang 5.0 or later (due to -Wunused-lambda-capture)

### ISSUE THREAD

**Issue by jbeich** [MerryMage/dynarmic#120]
```c++
$ c++ -v
FreeBSD clang version 5.0.0 (tags/RELEASE_500/final 312559) (based on LLVM 5.0.0svn)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin

$ pkg install git cmake ninja boost-libs
$ git clone https://github.com/MerryMage/dynarmic
$ mkdir dynarmic_build; cd dynarmic_build
$ cmake -GNinja ../dynarmic
$ ninja
[...]
/tmp/dynarmic/src/frontend/translate/translate_arm/exception_generating.cpp:13:12: fatal error: lambda capture 'cond' is not used [-Wunused-lambda-capture]
    UNUSED(cond, imm12, imm4);
           ^
In file included from /tmp/dynarmic/src/frontend/disassembler/disassembler_thumb.cpp:16:
In file included from /tmp/dynarmic/src/./frontend/decoder/thumb16.h:14:
/tmp/dynarmic/src/./frontend/decoder/decoder_detail.h:118:25: fatal error: lambda capture 'arg_masks' is not used [-Wunused-lambda-capture]
            return [fn, arg_masks, arg_shifts](Visitor& v, opcode_type instruction) {
                        ^
```

**Comment by MerryMage** [comment]
Closed by 1d75664a.

**Comment by jbeich** [comment]
I confirm, dynarmic builds fine with Clang 5.0 now.
